/**
 * AdForge CLI — Campaign Storage Module
 *
 * Saves/loads campaigns as JSON files locally.
 * All campaigns stored in: ./cli/campaigns/
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CAMPAIGNS_DIR = path.join(__dirname, "campaigns");

// Ensure campaigns directory exists
if (!fs.existsSync(CAMPAIGNS_DIR)) {
  fs.mkdirSync(CAMPAIGNS_DIR, { recursive: true });
}

function generateId() {
  return "camp_" + Date.now().toString(36) + "_" + Math.random().toString(36).slice(2, 7);
}

function slugify(str) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
}

/**
 * Save a campaign to disk
 */
export function saveCampaign(campaign, meta = {}) {
  const id = generateId();
  const slug = slugify(campaign.productName || "untitled");
  const filename = `${id}_${slug}.json`;
  const filepath = path.join(CAMPAIGNS_DIR, filename);

  const record = {
    id,
    productName: campaign.productName,
    createdAt: new Date().toISOString(),
    provider: meta.provider || "deepseek",
    tone: meta.tone || "professional",
    platforms: meta.platforms || [],
    generation: campaign,
    tokensUsed: meta.tokensUsed || 0,
    cost: meta.cost || 0,
    favorite: false,
    rating: null,
    notes: "",
  };

  fs.writeFileSync(filepath, JSON.stringify(record, null, 2));
  return { id, filename, filepath };
}

/**
 * List all saved campaigns
 */
export function listCampaigns() {
  if (!fs.existsSync(CAMPAIGNS_DIR)) return [];

  const files = fs.readdirSync(CAMPAIGNS_DIR).filter(f => f.endsWith(".json"));

  return files.map(f => {
    try {
      const raw = fs.readFileSync(path.join(CAMPAIGNS_DIR, f), "utf-8");
      return JSON.parse(raw);
    } catch {
      return null;
    }
  }).filter(Boolean).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
}

/**
 * Get a specific campaign by ID
 */
export function getCampaign(id) {
  const campaigns = listCampaigns();
  return campaigns.find(c => c.id === id) || null;
}

/**
 * Update a campaign
 */
export function updateCampaign(id, updates) {
  const campaigns = listCampaigns();
  const campaign = campaigns.find(c => c.id === id);
  if (!campaign) return null;

  const updated = { ...campaign, ...updates };
  const slug = slugify(campaign.productName || "untitled");
  const filename = `${id}_${slug}.json`;
  const filepath = path.join(CAMPAIGNS_DIR, filename);

  // Check for old filename pattern
  if (!fs.existsSync(filepath)) {
    const oldFile = fs.readdirSync(CAMPAIGNS_DIR).find(f => f.startsWith(id));
    if (oldFile) {
      fs.writeFileSync(path.join(CAMPAIGNS_DIR, oldFile), JSON.stringify(updated, null, 2));
      return updated;
    }
    return null;
  }

  fs.writeFileSync(filepath, JSON.stringify(updated, null, 2));
  return updated;
}

/**
 * Delete a campaign
 */
export function deleteCampaign(id) {
  const files = fs.readdirSync(CAMPAIGNS_DIR);
  const target = files.find(f => f.startsWith(id));
  if (target) {
    fs.unlinkSync(path.join(CAMPAIGNS_DIR, target));
    return true;
  }
  return false;
}

/**
 * Export campaign as Markdown
 */
export function exportMarkdown(campaign) {
  const g = campaign.generation || campaign;
  const lines = [
    `# ${campaign.productName || "Ad Campaign"}`,
    "",
    `> Generated by AdForge CLI | ${new Date(campaign.createdAt || Date.now()).toLocaleDateString()}`,
    "",
    `---`,
    "",
    `## Headline`,
    "",
    g.headline || "N/A",
    "",
    `## Tagline`,
    "",
    `*${g.tagline || "N/A"}*`,
    "",
    `## Ad Copy`,
    "",
    g.adCopy || "N/A",
    "",
    `## Call to Action`,
    "",
    `**${g.callToAction || "N/A"}**`,
    "",
    `## Target Audience`,
    "",
    g.targetAudience || "N/A",
    "",
    `## Key Benefits`,
    "",
    ...(g.keyBenefits || "").split("|").map(b => `- ${b.trim()}`),
    "",
  ];

  // Platform versions
  if (g.platformVersions) {
    try {
      const pv = typeof g.platformVersions === "string" ? JSON.parse(g.platformVersions) : g.platformVersions;
      lines.push(`## Platform Versions`, "");
      for (const [platform, content] of Object.entries(pv)) {
        lines.push(`### ${platform.charAt(0).toUpperCase() + platform.slice(1)}`, "");
        if (typeof content === "object") {
          for (const [key, val] of Object.entries(content)) {
            lines.push(`**${key}:** ${val}`, "");
          }
        } else {
          lines.push(String(content), "");
        }
        lines.push("");
      }
    } catch {
      lines.push(`## Platform Versions`, "", String(g.platformVersions), "");
    }
  }

  // Meta
  lines.push("---", "");
  lines.push(`*Provider: ${campaign.provider || "deepseek"} | Tone: ${campaign.tone || "professional"} | Tokens: ${campaign.tokensUsed || 0}*`);

  return lines.join("\n");
}

/**
 * Export campaign as plain text
 */
export function exportText(campaign) {
  const g = campaign.generation || campaign;
  return [
    `CAMPAIGN: ${campaign.productName}`,
    "",
    `HEADLINE: ${g.headline}`,
    `TAGLINE: ${g.tagline}`,
    "",
    `AD COPY:`,
    g.adCopy,
    "",
    `CTA: ${g.callToAction}`,
    `AUDIENCE: ${g.targetAudience}`,
    "",
    `KEY BENEFITS: ${g.keyBenefits}`,
    "",
    `PLATFORM VERSIONS: ${g.platformVersions}`,
  ].join("\n");
}

/**
 * Save exported file
 */
export function saveExport(content, filename) {
  const filepath = path.join(CAMPAIGNS_DIR, "..", "exports", filename);
  const dir = path.dirname(filepath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filepath, content);
  return filepath;
}
